### ISSUE TITLE
[BUG]: Auto Smelt Broken

### ISSUE THREAD

**Issue by Rover12782** [Rover12782/uhc-dp#3]
**Describe the bug**
Since 1.17 auto smelt has been broken due to the introduction of 'raw ores'.

**To Reproduce**
Enable auto smelt, and mine an Iron Ore/Gold Ore block

**Expected behaviour**
The smelted version of the ore should drop

**Screenshots**
N/A

**Environment**
 - Minecraft Version: 1.17+
 - Pack Version: v3.2.4

**Additional context**
N/A

**Comment by GalaxyGamerMC** [comment]
Fixed in #24
